package app

import (
	"errors"
	"html/template"
	"net/http"
	"strings"

	"github.com/yourorg/ntfywui/internal/qr"
	"github.com/yourorg/ntfywui/internal/security"
	"github.com/yourorg/ntfywui/internal/store"
)

type accountData struct {
	Me            store.Admin
	PendingSecret string // formatted in groups of 4
	PendingURI    string
	PendingQR     template.HTML
}

func (s *Server) handleAccount(w http.ResponseWriter, r *http.Request) {
	me := adminFrom(r)
	d := accountData{Me: me}
	if me.TOTPPending != "" {
		d.PendingURI = security.OTPAuthURI("ntfywui", me.Username, me.TOTPPending)
		if code, err := qr.Encode([]byte(d.PendingURI)); err == nil {
			// The SVG is generated by our own encoder from a fixed alphabet; safe to embed.
			d.PendingQR = template.HTML(code.SVG())
		}
		d.PendingSecret = groupBy4(me.TOTPPending)
	}
	s.page(w, r, http.StatusOK, "account", Page{
		Title:    "Mein Konto",
		Subtitle: "Passwort und Zwei-Faktor-Authentifizierung",
		Nav:      "account",
		Admin:    me,
		Data:     d,
	})
}

func groupBy4(s string) string {
	var b strings.Builder
	for i, c := range s {
		if i > 0 && i%4 == 0 {
			b.WriteByte(' ')
		}
		b.WriteRune(c)
	}
	return b.String()
}

func (s *Server) handleAccountPost(w http.ResponseWriter, r *http.Request) {
	me := adminFrom(r)
	switch r.PostFormValue("action") {
	case "password":
		cur := r.PostFormValue("current")
		pass := r.PostFormValue("password")
		if _, err := s.admins.CheckPassword(me.Username, cur); err != nil {
			s.fail(w, r, "/account", "Das aktuelle Passwort ist falsch.")
			return
		}
		if len(pass) < minPasswordLen {
			s.fail(w, r, "/account", "Das neue Passwort muss mindestens 8 Zeichen lang sein.")
			return
		}
		if pass != r.PostFormValue("confirm") {
			s.fail(w, r, "/account", "Die Passwörter stimmen nicht überein.")
			return
		}
		hash := security.HashPassword(pass)
		a, err := s.admins.Update(me.Username, func(a *store.Admin) error { a.PassHash = hash; return nil })
		if err != nil {
			s.fail(w, r, "/account", err)
			return
		}
		s.auditEvent(r, "account_change_pass", me.Username, nil)
		s.refreshSession(w, r, a, "Dein Passwort wurde geändert. Andere Sitzungen wurden abgemeldet.")

	case "totp-begin":
		secret, err := security.GenerateTOTPSecret()
		if err != nil {
			s.fail(w, r, "/account", err)
			return
		}
		if _, err := s.admins.Update(me.Username, func(a *store.Admin) error { a.TOTPPending = secret; return nil }); err != nil {
			s.fail(w, r, "/account", err)
			return
		}
		http.Redirect(w, r, s.abs("/account#twofa"), http.StatusSeeOther)

	case "totp-cancel":
		_, _ = s.admins.Update(me.Username, func(a *store.Admin) error { a.TOTPPending = ""; return nil })
		s.done(w, r, "/account", "Einrichtung der Zwei-Faktor-Authentifizierung abgebrochen.")

	case "totp-confirm":
		a, err := s.admins.CheckTOTP(me.Username, r.PostFormValue("code"), true)
		if err != nil {
			if errors.Is(err, store.ErrInvalidTOTP) {
				s.fail(w, r, "/account#twofa", "Der Code ist ungültig. Prüfe die Uhrzeit deines Geräts und versuche es erneut.")
			} else {
				s.fail(w, r, "/account", err)
			}
			return
		}
		s.auditEvent(r, "webui_admin_2fa_enable", me.Username, nil)
		s.refreshSession(w, r, a, "Zwei-Faktor-Authentifizierung ist jetzt aktiv.")

	case "totp-disable":
		if _, err := s.admins.CheckPassword(me.Username, r.PostFormValue("current")); err != nil {
			s.fail(w, r, "/account", "Das Passwort ist falsch.")
			return
		}
		a, err := s.admins.Update(me.Username, func(a *store.Admin) error {
			a.TOTPSecret, a.TOTPPending, a.TOTPLast = "", "", 0
			return nil
		})
		if err != nil {
			s.fail(w, r, "/account", err)
			return
		}
		s.auditEvent(r, "webui_admin_2fa_disable", me.Username, nil)
		s.refreshSession(w, r, a, "Zwei-Faktor-Authentifizierung wurde deaktiviert.")

	default:
		s.fail(w, r, "/account", "Unbekannte Aktion.")
	}
}

// refreshSession updates the auth stamp of the current session after a
// credential change, so that only this session stays logged in.
func (s *Server) refreshSession(w http.ResponseWriter, r *http.Request, a store.Admin, msg string) {
	sess, _ := s.sessions.Get(r)
	sess.Stamp = a.Stamp()
	sess.Flash = &security.Flash{Kind: "success", Msg: msg}
	_ = s.sessions.Save(w, sess)
	http.Redirect(w, r, s.abs("/account"), http.StatusSeeOther)
}
